# Generated by Django 6.0.1 on 2026-01-30 01:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=17)),
                ('bbc', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=50)),
                ('published_city', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('pages', models.IntegerField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookCopyCondition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(null=True, unique=True, verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=30, null=True, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('place_of_study', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('bookcopy_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_number', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('condition', models.ForeignKey(db_column='condition_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookcopycondition')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(default=datetime.date(2026, 1, 30))),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_copy', models.ForeignKey(db_column='bookcopy_id', on_delete=django.db.models.deletion.CASCADE, to='core.bookcopy')),
                ('reader', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='core.reader')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('hashed_password', models.CharField(max_length=20)),
                ('reader', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='core.reader')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
    ]
