# Generated by Django 6.0.1 on 2026-01-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookcopy',
            table='bookcopy',
        ),
        migrations.AlterModelTable(
            name='bookcopycondition',
            table='bookcopycondition',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
        migrations.AlterModelTable(
            name='reader',
            table='reader',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
