# Generated by Django 6.0.1 on 2026-02-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bookcopy_table_alter_bookcopycondition_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='issue_date',
            field=models.DateField(default=datetime.date(2026, 2, 3)),
        ),
    ]
