# Generated by Django 6.0.1 on 2026-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loan_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('date_time', models.CharField(max_length=40)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
