# Generated by Django 6.0.1 on 2026-02-03 16:18

import core.models.book_copy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.IntegerField(default=core.models.book_copy.get_next_number, unique=True),
        ),
    ]
